/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/Button/Button.vue')['default']
    Card: typeof import('./src/components/Card/Card.vue')['default']
    CardHeader: typeof import('./src/components/Card/CardHeader.vue')['default']
    CardInner: typeof import('./src/components/Card/CardInner.vue')['default']
    CardTester: typeof import('./src/components/test/card-tester.vue')['default']
    Primitive: typeof import('radix-vue')['Primitive']
    TypographyTester: typeof import('./src/components/test/typography-tester.vue')['default']
  }
}
