/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppLayout: typeof import('./src/components/AppLayout/AppLayout.vue')['default']
    Button: typeof import('./src/components/Button/Button.vue')['default']
    Card: typeof import('./src/components/Card/Card.vue')['default']
    CardHeader: typeof import('./src/components/Card/CardHeader.vue')['default']
    CardInner: typeof import('./src/components/Card/CardInner.vue')['default']
    CardTester: typeof import('./src/components/test/card-tester.vue')['default']
    Checkbox: typeof import('./src/components/Checkbox/Checkbox.vue')['default']
    CheckboxIndicator: typeof import('radix-vue')['CheckboxIndicator']
    CheckboxRoot: typeof import('radix-vue')['CheckboxRoot']
    ComboboxContent: typeof import('radix-vue')['ComboboxContent']
    ComboboxEmpty: typeof import('radix-vue')['ComboboxEmpty']
    ComboboxGroup: typeof import('radix-vue')['ComboboxGroup']
    ComboboxInput: typeof import('radix-vue')['ComboboxInput']
    ComboboxItem: typeof import('radix-vue')['ComboboxItem']
    ComboboxLabel: typeof import('radix-vue')['ComboboxLabel']
    ComboboxRoot: typeof import('radix-vue')['ComboboxRoot']
    Icon: typeof import('./src/components/Icon/Icon.vue')['default']
    Input: typeof import('./src/components/Input/Input.vue')['default']
    InputGroup: typeof import('./src/components/Input/InputGroup.vue')['default']
    Menu: typeof import('./src/components/Menu/Menu.vue')['default']
    MenuItem: typeof import('./src/components/Menu/MenuItem.vue')['default']
    PreviewAlerts: typeof import('@/previews/alerts.vue')['default']
    Primitive: typeof import('radix-vue')['Primitive']
    TypographyTester: typeof import('./src/components/test/typography-tester.vue')['default']
    VunorComboboxInput: typeof import('./src/components/Combobox/VunorComboboxInput.vue')['default']
    VunorComboBoxInput: typeof import('./src/components/ComboBox/VunorComboBoxInput.vue')['default']
  }
}
