/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/Button/Button.vue')['default']
    Card: typeof import('./src/components/Button/Card.vue')['default']
    CardTester: typeof import('./src/components/card-tester.vue')['default']
    Primitive: typeof import('radix-vue')['Primitive']
  }
}
